package com.model;
// Generated Nov 20, 2015 9:48:42 PM by Hibernate Tools 4.3.1



/**
 * Contacts generated by hbm2java
 */
public class Contacts  implements java.io.Serializable {


     private Integer contactId;
     private String firstName;
     private String lastName;
     private byte[] photo;

    public Contacts() {
    }

    public Contacts(String firstName, String lastName, byte[] photo) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.photo = photo;
    }
   
    public Integer getContactId() {
        return this.contactId;
    }
    
    public void setContactId(Integer contactId) {
        this.contactId = contactId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }




}


