package com.model;
// Generated Nov 27, 2015 1:28:42 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private String userPassword;
     private String userMyname;

    public User() {
    }

    public User(String userName, String userPassword, String userMyname) {
       this.userName = userName;
       this.userPassword = userPassword;
       this.userMyname = userMyname;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getUserMyname() {
        return this.userMyname;
    }
    
    public void setUserMyname(String userMyname) {
        this.userMyname = userMyname;
    }




}


