package com.model;
// Generated Oct 22, 2015 11:07:40 PM by Hibernate Tools 4.3.1



/**
 * Logintable generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int id;
     private String password;
     private String ten;

    public User() {
    }

	
    public User(int id) {
        this.id = id;
    }
    public User(int id, String password, String ten) {
       this.id = id;
       this.password = password;
       this.ten = ten;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }




}


