package com.model;
// Generated Nov 13, 2016 2:24:56 PM by Hibernate Tools 4.3.1



/**
 * Properties generated by hbm2java
 */
public class Properties  implements java.io.Serializable {


     private Integer id;
     private Table table;
     private String name;
     private String type;
     private boolean required;
     private boolean PPrimary;
     private boolean PUnique;

    public Properties() {
    }

    public Properties(Table table, String name, String type, boolean required, boolean PPrimary, boolean PUnique) {
       this.table = table;
       this.name = name;
       this.type = type;
       this.required = required;
       this.PPrimary = PPrimary;
       this.PUnique = PUnique;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Table getTable() {
        return this.table;
    }
    
    public void setTable(Table table) {
        this.table = table;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public boolean isRequired() {
        return this.required;
    }
    
    public void setRequired(boolean required) {
        this.required = required;
    }
    public boolean isPPrimary() {
        return this.PPrimary;
    }
    
    public void setPPrimary(boolean PPrimary) {
        this.PPrimary = PPrimary;
    }
    public boolean isPUnique() {
        return this.PUnique;
    }
    
    public void setPUnique(boolean PUnique) {
        this.PUnique = PUnique;
    }




}


