package com.model;
// Generated Nov 13, 2016 2:24:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sqlfile generated by hbm2java
 */
public class Sqlfile  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set tables = new HashSet(0);

    public Sqlfile() {
    }

	
    public Sqlfile(String name) {
        this.name = name;
    }
    public Sqlfile(String name, Set tables) {
       this.name = name;
       this.tables = tables;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getTables() {
        return this.tables;
    }
    
    public void setTables(Set tables) {
        this.tables = tables;
    }




}


